"""enforce security uniqueness

Revision ID: 7642e3454034
Revises: fa990192e26f
Create Date: 2026-08-13 17:07:26.978946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7642e3454034'
down_revision: Union[str, Sequence[str], None] = 'fa990192e26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_security_company_symbol', 'securities', ['company_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_security_company_symbol', 'securities', type_='unique')
    # ### end Alembic commands ###
